# git-cliff ~ configuration file for the version bump, the changelog is configured in cliff.toml
# https://git-cliff.org/docs/configuration

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = true
# An array of regex based parsers for extracting data from the commit message.
commit_parsers = [{ field = "merge_commit", pattern = "true", skip = true }]
# Regex to select git tags that represent releases.
tag_pattern = "v[0-9].*"

[bump]
# Bump the major version for breaking changes even while the major version is 0.
breaking_always_bump_major = false
# The version to use when no tags are found.
initial_tag = "v0.0.1"
