# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Debug

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dump-env:
    name: Dump Env
    runs-on: ubuntu-latest
    steps:
      - name: Dump Env
        shell: bash
        run: |
          env
