name: Renovate
on:
  push:
    branches:
      - main
  # The "*" (#42, asterisk) character has special semantics in YAML, so this
  # string has to be quoted.
  schedule:
    - cron: "0 * * * *"
  # Manual trigger is also possible
  workflow_dispatch:
    inputs:
      log_level:
        description: "Log level"
        required: false
        default: "info"
        type: choice
        options:
          - info
          - debug
          - warn

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false

      - name: Run Renovate
        uses: renovatebot/github-action@53bdcc4ec92f28e5023ac92356ea8bb45f8b807d # v43.0.15
        env:
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          LOG_LEVEL: ${{ github.event.inputs.log_level || 'info' }}
        with:
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          renovate-version: 41.124.1
          configurationFile: .github/renovate-config.json
          token: "${{ steps.app-token.outputs.token }}"
        #   mount-docker-socket: true
